spring:
  config:
    import: "vault://"
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: tx-aggregate-categorize-service
  datasource:
    url: jdbc:h2:mem:transactionsDB
    driver-class-name: org.h2.Driver
    username: kapitek
    password: kapitek
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tx-aggregate-categorize-service
          jwk-set-uri: http://localhost:8080/realms/tx-aggregate-categorize-service/protocol/openid-connect/certs

kapitek:
  customer:
    info:
      url: http://localhost:8081/kapitek-cif/info
      auth:
        client-id: kapitek-tx-aggregate-categorize-service
        client-secret: kapitek-tx-aggregate-categorize-service
        grant-type: client_credentials
        url: http://localhost:8080/realms/payments-gateway/protocol/openid-connect/token

  datasource:
    transaction:
      account:
        auth:
          client-id: kapitek-tx-aggregate-categorize-service
          client-secret: kapitek-tx-aggregate-categorize-service
          grant-type: client_credentials
          url: http://localhost:8080/realms/payments-gateway/protocol/openid-connect/token
        url: http://localhost:8081/kapitek-account/transactions
      card:
        auth:
          client-id: kapitek-tx-aggregate-categorize-service
          client-secret: kapitek-tx-aggregate-categorize-service
          grant-type: client_credentials
          url: http://localhost:8080/realms/payments-gateway/protocol/openid-connect/token
        url: http://localhost:8081/kapitek-card/transactions


server:
  port: 8082